require('./style.scss')
var React = require('react')
var ReactDOM = require('react-dom')
var {Router,Route,Link} = require('react-router')
var $ = require('jquery')
var routes = require('./routes')
ReactDOM.render(<Router routes={routes}/>, $('#react-root')[0])